# Generated by Django 5.0 on 2024-12-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_tool', models.CharField(max_length=60)),
                ('type_tool', models.CharField(max_length=60)),
                ('working_length_tool', models.IntegerField()),
                ('length_tool', models.IntegerField()),
            ],
        ),
    ]
