# Generated by Django 5.2.2 on 2025-06-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='photo_url',
            field=models.URLField(null=True, verbose_name='URL фото'),
        ),
    ]
