# Generated by Django 5.0 on 2025-01-20 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_detail_order_tool_detail_detail_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='tools.order'),
        ),
    ]
