# Generated by Django 5.0 on 2025-01-22 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_alter_detail_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='order',
            new_name='order_id',
        ),
    ]
