# Generated by Django 5.0 on 2025-01-26 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_rename_order_detail_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacion', to='tools.detail')),
            ],
        ),
    ]
