# Generated by Django 5.0 on 2025-01-26 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_operation_delete_operacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='detail',
        ),
        migrations.AddField(
            model_name='tool',
            name='article',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='tool',
            name='operation_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tool', to='tools.operation'),
        ),
    ]
