# Generated by Django 5.0 on 2025-02-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0010_category_tools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tools',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='tools',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Tools',
        ),
    ]
