# Generated by Django 5.0 on 2025-03-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0011_remove_tools_cat_remove_tools_user_delete_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
        migrations.AddField(
            model_name='tool',
            name='material_of_detail',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='material_of_tool',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='short_description',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
