# Generated by Django 5.0 on 2025-03-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0012_tool_description_tool_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='diametr',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tool',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
