# Generated by Django 5.0 on 2025-03-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0013_tool_diametr_alter_tool_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='short_description',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
