# Generated by Django 5.0 on 2025-03-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0014_alter_tool_description_alter_tool_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='image_url',
            field=models.ImageField(blank=True, default='media/images/nophoto.jpg', null=True, upload_to='images'),
        ),
    ]
