# Generated by Django 5.0 on 2025-03-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0015_alter_tool_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='image_url',
            field=models.ImageField(blank=True, default='images/nophoto.jpg', null=True, upload_to='images'),
        ),
    ]
