# Generated by Django 5.2.2 on 2025-07-01 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_tool_created_at_tool_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='photo_url',
        ),
    ]
